# Generated by Django 4.2.6 on 2024-01-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_remove_code_markdown_code_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='semester',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
