# Generated by Django 4.2.6 on 2024-01-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_code_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='language',
            field=models.CharField(choices=[('Python', 'python'), ('CSS', 'css'), ('HTML', 'html'), ('Git', 'git'), ('React', 'react'), ('JavaScript', 'js')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
