# Generated by Django 4.2.6 on 2024-01-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_code_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('css', 'CSS'), ('html', 'HTML'), ('git', 'Git'), ('react', 'React'), ('js', 'JavaScript')], max_length=20),
        ),
    ]
