# Generated by Django 4.2.6 on 2024-01-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_rename_semester_code_tags_code_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='snippet_image',
            field=models.ImageField(default='default_image.jpg', upload_to='snippet_images'),
        ),
    ]
