# Generated by Django 4.2.6 on 2024-01-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_code_snippet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
