# Generated by Django 4.2.6 on 2024-01-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_code_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='definition_language',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
