# Generated by Django 4.2.6 on 2024-01-28 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_code_definition_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='definition_language',
            new_name='short_definition',
        ),
    ]
