# Generated by Django 4.2.6 on 2024-01-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_rename_definition_language_code_short_definition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelTable(
            name='code',
            table='Code',
        ),
    ]
