# Generated by Django 4.2.6 on 2024-01-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0012_alter_code_options_alter_code_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='tags',
            field=models.CharField(default='Snippet', max_length=40),
        ),
    ]
