# Generated by Django 4.2.6 on 2024-01-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0013_alter_code_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='snippet_image',
            field=models.ImageField(default='default.jpg', upload_to='snippet_images'),
        ),
    ]
