# Generated by Django 4.2.6 on 2024-01-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0015_alter_code_snippet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='snippet_image',
            field=models.ImageField(default='snippet_images/default.jpg', upload_to='snippet_images'),
        ),
    ]
